# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Ming_Jian/16QAM/16M_16QAM/zed_9361_1107_1Msys/zed_9361_1107_1Msys/zed_9361.srcs/sources_1/ip/blk_mem_gen_I/blk_mem_gen_I.xci
# IP: The module: 'blk_mem_gen_I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ming_Jian/16QAM/16M_16QAM/zed_9361_1107_1Msys/zed_9361_1107_1Msys/zed_9361.srcs/sources_1/ip/blk_mem_gen_I/blk_mem_gen_I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_I'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/Ming_Jian/16QAM/16M_16QAM/zed_9361_1107_1Msys/zed_9361_1107_1Msys/zed_9361.srcs/sources_1/ip/blk_mem_gen_I/blk_mem_gen_I.xci
# IP: The module: 'blk_mem_gen_I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ming_Jian/16QAM/16M_16QAM/zed_9361_1107_1Msys/zed_9361_1107_1Msys/zed_9361.srcs/sources_1/ip/blk_mem_gen_I/blk_mem_gen_I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_I'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
