# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Ming_Jian/16QAM/16M_16QAM/zed_9361_1107_1Msys/zed_9361_1107_1Msys/zed_9361.srcs/sources_1/ip/fifo_36x1024/fifo_36x1024.xci
# IP: The module: 'fifo_36x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ming_Jian/16QAM/16M_16QAM/zed_9361_1107_1Msys/zed_9361_1107_1Msys/zed_9361.srcs/sources_1/ip/fifo_36x1024/fifo_36x1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_36x1024'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Ming_Jian/16QAM/16M_16QAM/zed_9361_1107_1Msys/zed_9361_1107_1Msys/zed_9361.srcs/sources_1/ip/fifo_36x1024/fifo_36x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_36x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/Ming_Jian/16QAM/16M_16QAM/zed_9361_1107_1Msys/zed_9361_1107_1Msys/zed_9361.srcs/sources_1/ip/fifo_36x1024/fifo_36x1024.xci
# IP: The module: 'fifo_36x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Ming_Jian/16QAM/16M_16QAM/zed_9361_1107_1Msys/zed_9361_1107_1Msys/zed_9361.srcs/sources_1/ip/fifo_36x1024/fifo_36x1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_36x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Ming_Jian/16QAM/16M_16QAM/zed_9361_1107_1Msys/zed_9361_1107_1Msys/zed_9361.srcs/sources_1/ip/fifo_36x1024/fifo_36x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_36x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
