# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\ui\analyzer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 687)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("* {\n"
"    font-family: \"Segoe UI\", \"Microsoft YaHei\", sans-serif;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"\n"
"QMainWindow, QWidget {\n"
"    background-color: #1a1f2c; /* 深蓝黑底 */\n"
"    color: #e0e0e0;            /* 浅灰字体 */\n"
"    font-family: \"Segoe UI\", \"Microsoft YaHei\", sans-serif;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"}\n"
"\n"
"QLineEdit, QTextEdit, QPlainTextEdit {\n"
"    background-color: #2a3244;\n"
"    border: 1px solid #3c4458;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    color: #ffffff;\n"
"    selection-background-color: #5c6a89;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #2a3244;\n"
"    border: 1px solid #3c4458;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    color: #ffffff;\n"
"    selection-background-color: #5c6a89;\n"
"}\n"
"\n"
"QMenuBar, QMenu {\n"
"    background-color: #202637;\n"
"    color: #e0e0e0;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #2e3a55;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #1a1f2c;\n"
"    color: #a0a0a0;\n"
"}\n"
"\n"
"QToolTip {\n"
"    background-color: #2e3b55;\n"
"    color: white;\n"
"    border: 1px solid #5a6780;\n"
"}\n"
"\n"
"\n"
"/* blue metal */\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #3a4a68,\n"
"        stop: 0.5 #2e3b55,\n"
"        stop: 1 #1d273a\n"
"    );\n"
"    border: 1px solid #0f1b2e;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    text-align: center;\n"
"    /*box-shadow: 0px 2px 5px rgba(0,0,0,0.6);*/\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #44597f,\n"
"        stop: 0.5 #344765,\n"
"        stop: 1 #1e2d44\n"
"    );\n"
"    border: 1px solid #2c3c5a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #1e2a3d,\n"
"        stop: 1 #0f1725\n"
"    );\n"
"    border: 1px solid #000000;\n"
"    padding-top: 7px;  /* Pressed visual effect */\n"
"    padding-bottom: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #444a5a;\n"
"    color: #999;\n"
"    border: 1px solid #333;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("/* 整体容器背景 */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #2e3b55;\n"
"    background-color: #1a1f2c;\n"
"    top: -1px;  /* 防止 border 被切断 */\n"
"}\n"
"\n"
"/* 标签栏区域背景 */\n"
"QTabBar {\n"
"    background-color: #1a1f2c;\n"
"}\n"
"\n"
"/* 普通标签样式 */\n"
"QTabBar::tab {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #3a4a68,\n"
"        stop: 0.5 #2e3b55,\n"
"        stop: 1 #1d273a\n"
"    );\n"
"    color: white;\n"
"    border: 1px solid #0f1b2e;\n"
"    border-bottom-color: #2e3b55; /* 合并边框 */\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"/* 选中的标签页 */\n"
"QTabBar::tab:selected {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #44597f,\n"
"        stop: 0.5 #344765,\n"
"        stop: 1 #1e2d44\n"
"    );\n"
"    border: 1px solid #3c4a64;\n"
"    border-bottom: 1px solid #1a1f2c; /* 与内容区背景融合 */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QTabBar::tab:hover {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #4e6086,\n"
"        stop: 1 #2e3a55\n"
"    );\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab1.sizePolicy().hasHeightForWidth())
        self.tab1.setSizePolicy(sizePolicy)
        self.tab1.setObjectName("tab1")
        self.gridLayout = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.plt_sweep_spectrum = PlotWidget(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plt_sweep_spectrum.sizePolicy().hasHeightForWidth())
        self.plt_sweep_spectrum.setSizePolicy(sizePolicy)
        self.plt_sweep_spectrum.setMinimumSize(QtCore.QSize(0, 100))
        self.plt_sweep_spectrum.setAutoFillBackground(False)
        self.plt_sweep_spectrum.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.plt_sweep_spectrum.setObjectName("plt_sweep_spectrum")
        self.label_2 = QtWidgets.QLabel(self.plt_sweep_spectrum)
        self.label_2.setGeometry(QtCore.QRect(70, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: yellow;\n"
"    background-color: black;\n"
"    border: 1px solid yellow;\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.plt_sweep_spectrum)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.plt_s21 = PlotWidget(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plt_s21.sizePolicy().hasHeightForWidth())
        self.plt_s21.setSizePolicy(sizePolicy)
        self.plt_s21.setMinimumSize(QtCore.QSize(0, 100))
        self.plt_s21.setAutoFillBackground(False)
        self.plt_s21.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.plt_s21.setObjectName("plt_s21")
        self.label_3 = QtWidgets.QLabel(self.plt_s21)
        self.label_3.setGeometry(QtCore.QRect(70, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: yellow;\n"
"    background-color: black;\n"
"    border: 1px solid yellow;\n"
"}\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.plt_s21)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(2, 2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab2.sizePolicy().hasHeightForWidth())
        self.tab2.setSizePolicy(sizePolicy)
        self.tab2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tab2.setObjectName("tab2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plt_cstl = PlotWidget(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plt_cstl.sizePolicy().hasHeightForWidth())
        self.plt_cstl.setSizePolicy(sizePolicy)
        self.plt_cstl.setMinimumSize(QtCore.QSize(0, 100))
        self.plt_cstl.setAutoFillBackground(False)
        self.plt_cstl.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.plt_cstl.setObjectName("plt_cstl")
        self.label_8 = QtWidgets.QLabel(self.plt_cstl)
        self.label_8.setGeometry(QtCore.QRect(80, 10, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    color: yellow;\n"
"    background-color: black;\n"
"    border: 1px solid yellow;\n"
"}\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.plt_cstl)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.plt_I = PlotWidget(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plt_I.sizePolicy().hasHeightForWidth())
        self.plt_I.setSizePolicy(sizePolicy)
        self.plt_I.setMinimumSize(QtCore.QSize(0, 100))
        self.plt_I.setAutoFillBackground(False)
        self.plt_I.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.plt_I.setObjectName("plt_I")
        self.label_9 = QtWidgets.QLabel(self.plt_I)
        self.label_9.setGeometry(QtCore.QRect(60, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    color: yellow;\n"
"    background-color: black;\n"
"    border: 1px solid yellow;\n"
"}\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.plt_I)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem2)
        self.plt_Q = PlotWidget(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plt_Q.sizePolicy().hasHeightForWidth())
        self.plt_Q.setSizePolicy(sizePolicy)
        self.plt_Q.setMinimumSize(QtCore.QSize(0, 100))
        self.plt_Q.setAutoFillBackground(False)
        self.plt_Q.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.plt_Q.setObjectName("plt_Q")
        self.label = QtWidgets.QLabel(self.plt_Q)
        self.label.setGeometry(QtCore.QRect(60, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: yellow;\n"
"    background-color: black;\n"
"    border: 1px solid yellow;\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.plt_Q)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(2, 2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem3)
        self.plt_spectrum = PlotWidget(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plt_spectrum.sizePolicy().hasHeightForWidth())
        self.plt_spectrum.setSizePolicy(sizePolicy)
        self.plt_spectrum.setMinimumSize(QtCore.QSize(0, 100))
        self.plt_spectrum.setAutoFillBackground(False)
        self.plt_spectrum.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.plt_spectrum.setObjectName("plt_spectrum")
        self.label_7 = QtWidgets.QLabel(self.plt_spectrum)
        self.label_7.setGeometry(QtCore.QRect(80, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    color: yellow;\n"
"    background-color: black;\n"
"    border: 1px solid yellow;\n"
"}\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.plt_spectrum)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(2, 1)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_conn = QtWidgets.QPushButton(self.centralwidget)
        self.btn_conn.setStyleSheet("")
        self.btn_conn.setObjectName("btn_conn")
        self.horizontalLayout_2.addWidget(self.btn_conn)
        self.lbl_conn_light = QtWidgets.QLabel(self.centralwidget)
        self.lbl_conn_light.setStyleSheet("QLabel#lbl_conn_light {\n"
"    background-color: #cccccc;       /* 默认：灰色（未连接） */\n"
"    border: 2px solid #222;\n"
"    border-radius: 10px;             /* 让其变成圆形 */\n"
"    min-width: 20px;\n"
"    min-height: 20px;\n"
"    max-width: 20px;\n"
"    max-height: 20px;\n"
"}\n"
"")
        self.lbl_conn_light.setText("")
        self.lbl_conn_light.setObjectName("lbl_conn_light")
        self.horizontalLayout_2.addWidget(self.lbl_conn_light)
        self.lbl_conn_state = QtWidgets.QLabel(self.centralwidget)
        self.lbl_conn_state.setObjectName("lbl_conn_state")
        self.horizontalLayout_2.addWidget(self.lbl_conn_state)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setStyleSheet("")
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout_3.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setStyleSheet("")
        self.btn_stop.setObjectName("btn_stop")
        self.verticalLayout_3.addWidget(self.btn_stop)
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setStyleSheet("")
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_3.addWidget(self.btn_save)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "扫频频谱"))
        self.label_3.setText(_translate("MainWindow", "传输散射系数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "多频分析"))
        self.label_8.setText(_translate("MainWindow", "星座图"))
        self.label_9.setText(_translate("MainWindow", "I 路数据"))
        self.label.setText(_translate("MainWindow", "Q 路数据"))
        self.label_7.setText(_translate("MainWindow", "单频频谱"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "单频分析"))
        self.btn_conn.setText(_translate("MainWindow", "连接 / 断开"))
        self.lbl_conn_state.setText(_translate("MainWindow", "未连接"))
        self.btn_start.setText(_translate("MainWindow", "开始运行"))
        self.btn_stop.setText(_translate("MainWindow", "停止运行"))
        self.btn_save.setText(_translate("MainWindow", "保存数据"))
from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    from PyQt5.QtWidgets import QApplication, QMainWindow

    app = QApplication(sys.argv)
    window = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec())