set_property SRC_FILE_INFO {cfile:F:/Ming_Jian/16QAM/16M_16QAM/zed_9361_1107_1Msys/zed_9361_1107_1Msys/zed_9361.srcs/fpga_pin.xdc rfile:../../../zed_9361.srcs/fpga_pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN T22  IOSTANDARD LVCMOS33} [get_ports ledb_trx1_o  ]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN T21  IOSTANDARD LVCMOS33} [get_ports ledg_trx1_o  ]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN U22  IOSTANDARD LVCMOS33} [get_ports ledr_trx1_o  ]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN U21  IOSTANDARD LVCMOS33} [get_ports ledb_trx2_o  ]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN V22  IOSTANDARD LVCMOS33} [get_ports ledg_trx2_o  ]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN W22  IOSTANDARD LVCMOS33} [get_ports ledr_trx2_o  ]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN F18  IOSTANDARD LVCMOS25} [get_ports  ad9361_spi_csn_o      ]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN E18  IOSTANDARD LVCMOS25} [get_ports  ad9361_spi_clk_o      ]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN E21  IOSTANDARD LVCMOS25} [get_ports  ad9361_spi_mosi_o     ]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D21  IOSTANDARD LVCMOS25} [get_ports  ad9361_spi_miso_i     ]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN G15  IOSTANDARD LVCMOS25} [get_ports  ad9361_en_agc_o      ]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN J20  IOSTANDARD LVCMOS25} [get_ports  ad9361_enable_o      ]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A16  IOSTANDARD LVCMOS25} [get_ports  ad9361_resetb_o      ]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN K21  IOSTANDARD LVCMOS25} [get_ports  ad9361_txnrx_o       ]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN G16  IOSTANDARD LVCMOS25} [get_ports  ad9361_sync_in_o     ]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN L18  IOSTANDARD LVCMOS25} [get_ports  ad9361_clk_out_o     ]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A18  IOSTANDARD LVCMOS25} [get_ports  ad9361_ctrl_in_o[0]   ]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN A19  IOSTANDARD LVCMOS25} [get_ports  ad9361_ctrl_in_o[1]   ]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN D22  IOSTANDARD LVCMOS25} [get_ports  ad9361_ctrl_in_o[2]   ]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN C22  IOSTANDARD LVCMOS25} [get_ports  ad9361_ctrl_in_o[3]   ]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN J22  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_clk_out_n     ]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN J21  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_clk_out_p     ]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN N18  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_data_out_n[0] ]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN N17  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_data_out_p[0] ]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN P21  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_data_out_n[1] ]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN P20  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_data_out_p[1] ]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN M17  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_data_out_n[2] ]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN L17  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_data_out_p[2] ]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN T19  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_data_out_n[3] ]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN R19  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_data_out_p[3] ]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN K20  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_data_out_n[4] ]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN K19  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_data_out_p[4] ]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN J17  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_data_out_n[5] ]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN J16  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_data_out_p[5] ]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN R21  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_frame_out_n   ]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN R20  IOSTANDARD LVDS_25 } [get_ports  ad9361_tx_frame_out_p   ]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN M20  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_clk_in_n      ]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN M19  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_clk_in_p      ]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN P18  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_data_in_n[0]  ]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN P17  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_data_in_p[0]  ]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN P22  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_data_in_n[1]  ]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN N22  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_data_in_p[1]  ]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN M22  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_data_in_n[2]  ]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN M21  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_data_in_p[2]  ]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN K18  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_data_in_n[3]  ]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN J18  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_data_in_p[3]  ]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN L22  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_data_in_n[4]  ]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN L21  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_data_in_p[4]  ]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN T17  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_data_in_n[5]  ]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN T16  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_data_in_p[5]  ]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN N20  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_frame_in_n    ]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN N19  IOSTANDARD LVDS_25  DIFF_TERM true} [get_ports  ad9361_rx_frame_in_p    ]
