# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/projects/vivado20192/ZED_AD9361_Sean_2019_2_066_1/soc_prj/zed_9361/zed_9361.srcs/sources_1/ip/div0/div0.xci
# IP: The module: 'div0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/projects/vivado20192/ZED_AD9361_Sean_2019_2_066_1/soc_prj/zed_9361/zed_9361.srcs/sources_1/ip/div0/div0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/projects/vivado20192/ZED_AD9361_Sean_2019_2_066_1/soc_prj/zed_9361/zed_9361.srcs/sources_1/ip/div0/div0.xci
# IP: The module: 'div0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/projects/vivado20192/ZED_AD9361_Sean_2019_2_066_1/soc_prj/zed_9361/zed_9361.srcs/sources_1/ip/div0/div0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
